Repository codervivek5/Formfil, pull requests merged in 2023-02, with the labels that each got.

#36 I have added service link-1 section
  service.html
  styles.css
Labels: documentation, good first issue, JWOC, first-come-first-serve, Medium

#17 Create Dashboard page with profile
  pages/base.html
  pages/dashboard.html
  pages/login.html
  pages/signup.html
  style/signup.css
Labels: enhancement, good first issue, JWOC, first-come-first-serve, Medium

#23 Create Logo #5
  img/logo.png
Labels: enhancement, good first issue, JWOC, first-come-first-serve, Easy

#37 favicon added
  .vscode/settings.json
  index.html
  pages/contact-us.html
  pages/dashboard.html
  pages/login.html
Labels: good first issue, JWOC, Easy

#60 I have added checkout page for the issue#25
  checkout page/candidate.css
  checkout page/candidate.html
  checkout page/image123.jpg
  checkout page/laptop.jpg
Labels: good first issue, JWOC, Easy

#55 Whichever page was active the home button was highlighted and underlined
  .vscode/settings.json
  index.html
  pages/base.html
  pages/contact-us.html
  pages/login.html
Labels: good first issue, JWOC, Easy

#62 made changes in#25
  new project/image123.png
  new project/project.css
  new project/project.html
Labels: good first issue, JWOC, first-come-first-serve, Easy

#66 Added full name and OTP button in login page
  img/loginuser.jpeg
  pages/login.html
  style/login.css
Labels: good first issue, JWOC, Medium

#74 New cart page
  img/formfill.png
  img/ticket.jpeg
  img/xerox.png
  index.html
  pages/cart.html
  style/cart-style.css
Labels: good first issue, JWOC, Easy

#73 Updated readme.md
  README.md
Labels: enhancement, good first issue, JWOC, Easy

#72 About Us page
  img/people.jpg
  img/people.png
  pages/about_us.html
  style/about_us.css
Labels: good first issue, JWOC, first-come-first-serve, Easy

#83 Scroll to top button
  index.html
  style/style.css
Labels: bug, good first issue, JWOC, Medium

#88 Broken-Cart image
  img/cart-image.png
  img/cart_img.png
  index.html
Labels: good first issue, JWOC, Easy

#89 ISSUE 15 : BUG-There is a bug in the navbar that when we are going through other page then also line is coming under home page. I want to correct it.
  index.html
  pages/about_us.html
  pages/contact-us.html
Labels: good first issue, JWOC, Easy

#98 README.md update
  README.md
Labels: documentation, enhancement, good first issue, JWOC, Easy

#94 Add about us page (Issue #45)
  pages/about_us.html
  style/about_us.css
Labels: documentation, good first issue, JWOC, Medium

#99 Issue #90 Form validations in contact_us page
  Formfil.in - Shortcut.lnk
  pages/contact-us.html
  style/contact-us.css
Labels: bug, good first issue, JWOC, Easy

#104 #97 interlinking all pages of html
  index.html
  landing.html
  pages/about_us.html
  pages/base.html
  pages/contact-us.html
  style/style.css
Labels: bug, enhancement, JWOC, Hard

#100 Dark Mode & Cart in all pages
  darkmode.js
  index.html
  pages/about_us.html
  pages/base.html
  pages/contact-us.html
  pages/dashboard.html
  style/about_us.css
Labels: bug, good first issue, JWOC, Medium

#109 #101 loader issue solved
  index.html
Labels: bug, enhancement, JWOC, Medium

#114 Login Page is added
  login.html
  login.jpg
Labels: good first issue, JWOC, Easy

#107 Fevicon zoomed in and added
  img/crop_logo.png
  index.html
  landing.html
  pages/about_us.html
  pages/candidate.html
  pages/cart.html
  pages/contact-us.html
  pages/dashboard.html
  pages/login.html
  pages/payment.html
  pages/project.html
  pages/service.html
  pages/signup.html
  pages/testimonial.html
  pages/user_dashboard.html
  pages/user_profile.html
Labels: bug, good first issue, JWOC, Medium

#120 Responsiveness added to Contact Us page
  pages/contact-us.html
  style/contact-us-handset.css
  style/contact-us.css
Labels: bug, good first issue, JWOC, Medium

#129 added content to home page
  index.html
  style/style.css
Labels: documentation, enhancement, good first issue, JWOC, Easy

#126 Updated File Structure Properly
  img/login.jpg
  index.html
  landing.html
  login.html
  pages/contact-us.html
  pages/home.html
  pages/login.html
  scripts/darkmode.js
  scripts/landing.js
  scripts/swiper-bundle.min.js
  scripts/testimonial.js
Labels: bug, good first issue, JWOC, Hard

#132 #113 footer solved
  index.html
  pages/about_us.html
  pages/contact-us.html
  pages/service.html
  pages/testimonial.html
  style/about_us.css
  style/contact-us.css
  style/services.css
  style/style.css
  style/testimonial.css
Labels: bug, good first issue, JWOC, Hard
