Repository codervivek5/Formfil, pull requests merged in 2023-03, with the labels that each got.

#138 Enhanced Navbar and Home CSS
  index.html
  pages/about_us.html
  pages/contact-us.html
  style/contact-us-handset.css
  style/contact-us.css
  style/style.css
  style/theme.css
Labels: good first issue, JWOC, Medium

#143 Contact details model added details from contactus form are getti…
  Django-FormFil/FormFil/FormFil/__pycache__/settings.cpython-38.pyc
  Django-FormFil/FormFil/FormFil/settings.py
  Django-FormFil/FormFil/db.sqlite3
  Django-FormFil/FormFil/home/__pycache__/admin.cpython-38.pyc
  Django-FormFil/FormFil/home/__pycache__/apps.cpython-38.pyc
  Django-FormFil/FormFil/home/__pycache__/models.cpython-38.pyc
  Django-FormFil/FormFil/home/__pycache__/views.cpython-38.pyc
  Django-FormFil/FormFil/home/admin.py
  Django-FormFil/FormFil/home/migrations/0001_initial.py
  Django-FormFil/FormFil/home/migrations/__pycache__/0001_initial.cpython-38.pyc
  Django-FormFil/FormFil/home/migrations/__pycache__/__init__.cpython-38.pyc
  Django-FormFil/FormFil/home/models.py
  Django-FormFil/FormFil/home/views.py
  Django-FormFil/FormFil/templates/contact-us.html
Labels: good first issue, JWOC, Medium

#147 Home Page UI
  index.html
  style/style.css
  style/theme.css
Labels: bug, good first issue, Medium

#153 Improved Footer
  Django-FormFil/FormFil/templates/about_us.html
  Django-FormFil/FormFil/templates/contact-us.html
  Django-FormFil/FormFil/templates/index.html
  index.html
  pages/about_us.html
  pages/contact-us.html
  pages/home.html
  pages/service.html
  pages/testimonial.html
  style/about_us.css
  style/base.css
  style/candidate.css
  style/cart-style.css
  style/contact-us-handset.css
  style/contact-us.css
  style/dashboard.css
  style/style.css
  style/testimonial.css
  style/theme.css
Labels: good first issue, JWOC, Medium

#167 Register details of user in user database
  Django-FormFil/FormFil/db.sqlite3
  Django-FormFil/FormFil/home/__pycache__/admin.cpython-38.pyc
  Django-FormFil/FormFil/home/__pycache__/models.cpython-38.pyc
  Django-FormFil/FormFil/home/__pycache__/views.cpython-38.pyc
  Django-FormFil/FormFil/home/admin.py
  Django-FormFil/FormFil/home/models.py
  Django-FormFil/FormFil/home/views.py
  Django-FormFil/FormFil/static/style/signup.css
  Django-FormFil/FormFil/templates/signup.html
Labels: good first issue, JWOC, Hard

#156 navbar enhanced
  index.html
  pages/about_us.html
  pages/cart.html
  pages/contact-us.html
  pages/home.html
  pages/service.html
  pages/testimonial.html
  style/navbar.css
  style/style.css
  style/testimonial.css
  style/theme.css
Labels: bug, good first issue, Medium

#174 Fixed issues
  pages/testimonial.html
  style/testimonial.css
Labels: good first issue, JWOC, Medium

#178 Added endpoint backend in contact us form
  pages/contact-us.html
Labels: Authentication, good first issue, JWOC, Hard

#193 Checking for already existing users and sending alert messages
  Django-FormFil/FormFil/db.sqlite3
  Django-FormFil/FormFil/home/__pycache__/urls.cpython-38.pyc
  Django-FormFil/FormFil/home/__pycache__/views.cpython-38.pyc
  Django-FormFil/FormFil/home/views.py
  Django-FormFil/FormFil/static/style/signup.css
  Django-FormFil/FormFil/templates/signup.html
Labels: Authentication, good first issue, JWOC, Hard

#180 Service cards theme updated
  style/services.css
Labels: good first issue, JWOC, Easy

#185 Added content in services cards
  pages/service.html
Labels: bug, good first issue, JWOC, Easy

#201 Update the contact links in the footer
  index.html
  pages/about_us.html
  pages/cart.html
  pages/contact-us.html
  pages/home.html
  pages/service.html
  pages/testimonial.html
Labels: good first issue, JWOC, Easy

#196 Badges Added
  README.md
Labels: enhancement, JWOC, first-come-first-serve, Easy

#176 Language Translator
  index.html
  pages/about_us.html
  pages/base.html
  pages/cart.html
  pages/contact-us.html
  pages/dashboard.html
  pages/home.html
  pages/service.html
  pages/testimonial.html
  pages/user_dashboard.html
  scripts/translate.js
  style/translate.css
Labels: good first issue, JWOC, Hard

#207 terms and conditions marked compulsory and needs to be filled before logging in"
  Django-FormFil/FormFil/db.sqlite3
  Django-FormFil/FormFil/templates/login.html
  Django-FormFil/FormFil/templates/loginemail.html
Labels: bug, good first issue, JWOC, Hard
